apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: otp-core
  namespace: opentripplanner
spec:
  hosts:
    - "my-app-service"
  http:
    - route:
        - destination:
            host: my-app-service
            subset: stable  
          weight: 100  
        - destination:
            host: my-app-service
            subset: canary  
          weight: 0 
