apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-manager
  namespace: opentripplanner  
rules:
  - apiGroups: [""]
    resources:
      - services
    verbs:
      - get
      - create
      - update
      - delete

