apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-io1
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2            
  fsType: ext4          
reclaimPolicy: Retain   
volumeBindingMode: WaitForFirstConsumer  

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ebs-io1  
