apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: opentripplanner
  namespace: opentripplanner
spec:
  replicas: 3  
  strategy:
    canary:
      steps:
        - setWeight: 10  
        - pause: {duration: 30s}  
        - setWeight: 50  
        - pause: {duration: 30s}  
        - setWeight: 100  
  selector:
    matchLabels:
      app: otp-core
  template:
    metadata:
      labels:
        app: otp-core
        version: canary  
    spec:
      containers:
        - name: otp-core
          image: openjdk:17-jdk-slim 
