apiVersion: apps/v1
kind: Deployment
metadata:
  name: otp-core
  namespace: opentripplanner
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: otp-core
      version: canary
  template:
    metadata:
      labels:
        app: otp-core
        version: canary
    spec:
      containers:
        - name: otp-core
          image: openjdk:18-jdk-slim  
          ports:
            - containerPort: 8080
