apiVersion: v1
kind: Service
metadata:
  name: otp-core
  namespace: opentripplanner
  labels:
    app: otp-core
spec:
  selector:
    app: otp-core
  ports:
    - name: http
      port: 80
      targetPort: 8080
